version: "3"
services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker --entryPoints.web.address=:80 --entryPoints.web.forwardedHeaders.insecure
    networks:
      - executeit
    ports:
      # The HTTP port
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build:
      context: .
    ports:
      - "5000"
    volumes:
      - ./:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - executeit
    command: >
      sh -c "pm2-runtime ecosystem.config.js"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DOCKER_SOCKET=/var/run/docker.sock
      - USER_SERVER_URL=rooms.executeit.ml
      - USER_SERVER_IMAGE=pnshiralkar/execute-it-user-image
      - USER_SERVER_CPU_LIMIT=10
      - USER_SERVER_MEM_LIMIT=256000
      - USER_SERVER_NETWORK=executeit
      - MONGO_HOST=mongo
      - MONGO_DB_NAME=executeit
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=https://api.executeit.ml/auth/google/callback
      - JWT_SECRET=gocoronago
      - OT_SERVER_URL=https://ot.executeit.ml/api/rest
      - FRONTEND_REDIRECT_URL=https://executeit.ml/callback
      - AUTH_SERVER_URL=https://api.executeit.ml/auth


    labels:
      - "traefik.http.routers.app.rule=Host(`api.executeit.ml`)"
  mongo:
    image: mongo
    restart: always
    networks:
      - executeit
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-volume:/data/db

  ot-server:
    image: convergencelabs/convergence-omnibus
    networks:
      - executeit
    volumes:
      - ./ot-volume:/orientdb/databases
    ports:
      - "80"
    labels:
      - "traefik.http.routers.ot-server.rule=Host(`ot.executeit.ml`)"

networks:
  executeit:
    external:
      name: executeit